---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-configserver
  labels:
    app: mongodb-configserver
spec:
  ports:
    - name: mongo
      port: 27017
  clusterIP: None
  selector:
    app: mongodb-configserver

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-mongodb-config-server-cluster-auth
spec:
  secretName: certificate-mongodb-config-server-cluster-auth
  issuerRef:
    name: mongodb-cluster-ca-issuer
    kind: Issuer
  subject:
    organizations:
      - organizationName
    organizationalUnits:
      - mongodb-configserver
  commonName: "mongodb-configserver.mongodb-configserver"
  dnsNames:
    - "mongodb-configserver.mongodb-configserver.default.svc.cluster.local"
    - "*.mongodb-configserver.default.svc.cluster.local"
    - "mongodb-configserver.mongodb-configserver"
  usages:
    - client auth
    - server auth

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-mongodb-config-server-root
spec:
  secretName: certificate-mongodb-config-server-root
  issuerRef:
    name: mongodb-cluster-ca-issuer
    kind: Issuer
  subject:
    organizations:
      - organizationName
    organizationalUnits:
      - administration
  commonName: "root"
  dnsNames:
    - "root"
  usages:
    - client auth

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-configserver
spec:
  selector:
    matchLabels:
      app: mongodb-configserver
  serviceName: mongodb-configserver
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb-configserver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4.2.9
          command:
            - "/bin/sh"
            - "-c"
            - |
              cat /certs-cluster-auth/tls.crt /certs-cluster-auth/tls.key > /cluster-auth.pem
              mongod \
                --configsvr \
                --replSet=cfgrs \
                --auth \
                --port=27017 \
                --dbpath=/data/db \
                --bind_ip_all \
                --tlsOnNormalPorts \
                --tlsCAFile=/certs-cluster-auth/ca.crt \
                --tlsCertificateKeyFile=/cluster-auth.pem \
                --tlsClusterFile=/cluster-auth.pem \
                --tlsClusterCAFile=/certs-cluster-auth/ca.crt \
                --clusterAuthMode=x509
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 30
            periodSeconds: 10
            successThreshold: 1
          ports:
            - containerPort: 27017
              name: configsvr
          volumeMounts:
            - name: mongo
              mountPath: /data/db
            - name: certs-cluster-auth
              mountPath: /certs-cluster-auth
            - name: certs-root
              mountPath: /certs-root
      volumes:
        - name: certs-cluster-auth
          secret:
            secretName: certificate-mongodb-config-server-cluster-auth
        - name: certs-root
          secret:
            secretName: certificate-mongodb-config-server-root
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
              weight: 5
  volumeClaimTemplates:
    - metadata:
        name: mongo
      spec:
        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: "storageclass"
        resources:
          requests:
            storage: 2Gi

---