---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-configserver
  labels:
    app: mongodb-configserver
spec:
  ports:
    - name: mongo
      port: 27017
  clusterIP: None
  selector:
    app: mongodb-configserver

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-configserver
spec:
  selector:
    matchLabels:
      app: mongodb-configserver
  serviceName: mongodb-configserver
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb-configserver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4.2.9
          command:
            - "mongod"
            - "--configsvr"
            - "--replSet=cfgrs"
            - "--port=27017"
            - "--dbpath=/data/db"
            - "--bind_ip_all"
          livenessProbe:
            exec:
              command:
                - "mongo"
                - "--eval"
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - "mongo"
                - "--eval"
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          ports:
            - containerPort: 27017
              name: configsvr
          volumeMounts:
            - name: mongo
              mountPath: /data/db
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
              weight: 5
  volumeClaimTemplates:
    - metadata:
        name: mongo
      spec:
        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: "storageclass"
        resources:
          requests:
            storage: 2Gi
---