---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-mongodb-ss-1-cluster-auth
spec:
  secretName: certificate-mongodb-ss-1-cluster-auth
  issuerRef:
    name: mongodb-cluster-ca-issuer
    kind: Issuer
  subject:
    organizations:
      - organizationName
    organizationalUnits:
      - organizationUnit
  commonName: "mongodb-ss-1.mongodb-ss-1.default.svc.cluster.local"
  dnsNames:
    - "mongodb-ss-1.mongodb-ss-1.default.svc.cluster.local"
    - "*.mongodb-ss-1.default.svc.cluster.local"
    - "mongodb-ss-1.mongodb-ss-1"
    - "*.mongodb-ss-1"
  usages:
    - client auth
    - server auth